package com.lets.platform.model.base.enums;

import com.lets.platform.common.pojo.enums.IEnum;

/**
 * 批量操作-异常提示代码
 */
public enum ErrorCodeEnum implements IEnum<Object> {

    SUCCESS("SU-0000"),
    FAIL("ER-0000"),
    FAIL_NOT_EXIST("ER-0001"),
    OPERATION_NOT_ALLOWED("ER-0002"),

    EXPORT_FAIL_BY_STATUS("ER-0003"),
    EXPORT_FAIL_BY_PRINT_TIMES("ER-0004"),
    EXPORT_FAIL_BY_HAS_NO_TEMPLATE("ER-0005"),

    ENABLE_SUCCESS("SU-0001"),
    ENABLE_FAIL_BY_ENABLE("ER-1001"),
    ENABLE_FAIL_BY_EXAMINE("ER-1002"),
    ENABLE_FAIL_BY_SYS_DATA("ER-1003"),
    ENABLE_FAIL_BY_FIND_NO_PARENT("ER-1004"),
    ENABLE_FAIL_BY_STATUS("ER-1005"),

    DISABLE_SUCCESS("SU-0002"),
    DISABLE_FAIL_BY_ENABLE("ER-2001"),
    DISABLE_FAIL_BY_EXAMINE("ER-2002"),
    DISABLE_FAIL_BY_SYS_DATA("ER-2003"),
    DISABLE_FAIL_BY_NOT_CHOSE_ALL_CHILD("ER-2004"),
    DISABLE_FAIL_BY_STATUS("ER-2005"),
    DISABLE_FAIL_BY_QUOTE("ER-2006"),

    DELETE_SUCCESS("SU-0003"),
    DELETE_FAIL_BY_QUOTE("ER-3001"),
    DELETE_FAIL_BY_STATUS("ER-3002"),
    DELETE_FAIL_BY_PRESETS("ER-3003"),
    DELETE_FAIL_BY_BASE_CURRENCY("ER-3004"),
    DELETE_FAIL_BY_SYS_DATA("ER-3005"),
    DELETE_FAIL_BY_NOT_CHOSE_ALL_CHILD("ER-3006"),

    SUBMIT_SUCCESS("SU-004"),
    SUBMIT_FAIL_BY_STATUS("ER-4001"),
    SUBMIT_FAIL_BY_EMPTY_DETAIL("ER-4002"),
    SUBMIT_FAIL_BY_NUMBER("ER-4003"),
    SUBMIT_FAIL_BY_PERIOD_WARNING("ER-4004"),
    SUBMIT_FAIL_BY_PERIOD_FORCE("ER-4005"),
    SUBMIT_FAIL_BY_BATCH("ER-4006"),
    SUBMIT_FAIL_BY_MATERIAL_TYPE("ER-4007"),
    SUBMIT_FAIL_BY_ORG_USER("ER-4008"),
    SUBMIT_FAIL_BY_SPECIFIC("ER-4009"),
    SUBMIT_FAIL_BY_UNIT("ER-4010"),
    SUBMIT_FAIL_BY_SOME_FIELD_REPEAT("ER-4011"),
    SUBMIT_FAIL_BY_CATEGORY_FIELD("ER-4012"),

    REVOKE_SUCCESS("SU-005"),
    REVOKE_FAIL_BY_STATUS("ER-5001"),
    REVOKE_FAIL_BY_NUMBER("ER-5002"),

    AUDIT_SUCCESS("SU-006"),
    AUDIT_FAIL_BY_STATUS("ER-6001"),

    REVERSE_SUCCESS("SU-007"),
    REVERSE_FAIL_BY_STATUS("ER-7001"),
    REVERSE_FAIL_BY_CLOSE("ER-7002"),
    REVERSE_FAIL_BY_DETAIL_CLOSE("ER-7003"),
    /** 下发 */
    ISSUE_SUCCESS("SU-009"),
    ISSUE_FAIL_BY_STATUS("ER-9012"),
    ISSUE_FAIL_BY_ISSUED("ER-9012"),
    ISSUE_FAIL("ER-9013"),
    REVERSE_FAIL_BY_QUOTE("ER-7004"),
    REVERSE_FAIL_BY_NUMBER("ER-7005"),

    POSTING_SUCCESS("SU-008"),
    POSTING_FAIL_BY_STATUS("ER-8001"),
    POSTING_FAIL_BY_CLOSE("ER-8002"),
    POSTING_FAIL_BY_DETAIL_CLOSE("ER-8003"),
    POSTING_FAIL_BY_QUOTE("ER-8004"),
    POSTING_FAIL_BY_NUMBER("ER-8005"),
    POSTING_FAIL_BY_STORE("ER-8006"),

    MATERIAL_UNIT_ERROR("ER-9001"),
    SALE_ORDER_ERROR("ER-9002"),
    DELIVERY_ORDER_ERROR("ER-9003"),
    SAlE_STOCK_OUT_ORDER_ERROR("ER-9004"),
    UNPLANNED_STOCK_IN_ORDER_ERROR("ER-9005"),
    UNPLANNED_STOCK_OUT_ORDER_ERROR("ER-9006"),
    INVENTORY_CHECK_ORDER_ERROR("ER-9007"),
    START_CHECK_SUCCESS("SU-010"),
    START_CHECK_ERROR("ER-9010"),
    CANCEL_CHECK_SUCCESS("SU-011"),
    CANCEL_CHECK_ERROR("ER-9011"),
    END_CHECK_SUCCESS("SU-012"),
    END_CHECK_ERROR("ER-9012"),
    WIP_COMPLETION_STOCK_INORDER_ERROR("ER-9013"),
    PURCHASE_PRICE_LIST_ERROR("ER-9014"),
    PURCHASE_APPLY_ORDER_ERROR("ER-9015"),

    /** 作废 */
    CANCEL_SUCCESS("SU-010"),
    CANCEL_FAIL_BY_STATUS("ER-1001"),
    CANCEL_FAIL_BY_QUOTE("ER-1002"),
    CANCEL_FAIL_BY_NUMBER("ER-1003"),
    /** 取消下发 */
    CANCEL_ISSUE_SUCCESS("SU-011"),
    CANCEL_ISSUE_FAIL_BY_STATUS("ER-1101"),
    CANCEL_ISSUE_FAIL_BY_PROCESS_PLAN("ER-1102"),
    /** 开工 */
    START_TO_WORK_SUCCESS("SU-012"),
    START_TO_WORK_FAIL_BY_STATUS("ER-1201"),
    START_TO_WORK_FAIL("ER-1202"),
    /** 取消开工 */
    STOP_TO_WORK_SUCCESS("SU-013"),
    STOP_TO_WORK_FAIL_BY_STATUS("ER-1301"),
    STOP_TO_WORK_FAIL("ER-1302"),
    /** 完工 */
    FINISH_WORK_SUCCESS("SU-014"),
    FINISH_WORK_FAIL_BY_STATUS("ER-1401"),
    /** 取消完工 */
    CANCEL_FINISH_WORK_SUCCESS("SU-015"),
    CANCEL_FINISH_WORK_FAIL_BY_STATUS("ER-1501"),
    /** 暂停 */
    SUSPEND_SUCCESS("SU-016"),
    SUSPEND_FAIL_BY_STATUS("ER-1601"),
    /** 恢复 */
    RECOVER_SUCCESS("SU-017"),
    RECOVER_FAIL_BY_STATUS("ER-1701"),
    RECOVER_FAIL("ER-1702"),
    /** 关闭 */
    CLOSE_SUCCESS("SU-018"),
    CLOSE_FAIL_BY_STATUS("ER-1801"),
    /** 重新开启 */
    RESTART_SUCCESS("SU-019"),
    RESTART_FAIL_BY_STATUS("ER-1901"),
    /** 确认 */
    CONFIRM_SUCCESS("SU-020"),
    CONFIRM_FAIL_BY_STATUS("ER-2001"),
    CONFIRM_FAIL_BY_ENABLE("ER-2002"),
    /** 取消确认 */
    CANCEL_CONFIRM_SUCCESS("SU-021"),
    CANCEL_CONFIRM_FAIL_BY_STATUS("ER-2101"),
    CANCEL_CONFIRM_FAIL_BY_ENABLE("ER-2102"),
    /** 投放 */
    PUT_IN_SUCCESS("SU-022"),
    PUT_IN_FAIL_BY_STATUS("ER-2201"),
    PUT_IN_FAIL_BY_ENABLE("ER-2202"),
    PUT_IN_FAIL_BY_AUTO_CODE("ER-2203"),
    /** 反作废 */
    REVERSE_CANCEL_SUCCESS("SU-023"),
    REVERSE_CANCEL_FAIL_BY_STATUS("ER-2301"),
    /** 计划 */
    PLAN_SUCCESS("SU-024"),
    PLAN_FAIL_BY_STATUS("ER-2401"),
    /** 取消计划 */
    CANCEL_PLAN_SUCCESS("SU-025"),
    CANCEL_PLAN_FAIL_BY_STATUS("ER-2501"),
    /** 下达 */
    RELEASE_SUCCESS("SU-026"),
    RELEASE_FAIL_BY_STATUS("ER-2601"),
    /** 取消下达 */
    CANCEL_RELEASE_SUCCESS("SU-027"),
    CANCEL_RELEASE_FAIL_BY_STATUS("ER-2701"),
    /** 派工*/
    DISPATCH_SUCCESS("SU_028"),
    DISPATCH_FAIL_BY_STATUS("ER-2801"),
    /** 发布 */
    DEPLOY_SUCCESS("SU-029"),
    DEPLOY_FAIL_BY_STATUS("ER-2901"),
    DEPLOY_FAIL_BY_EXIST_DEPLOY("ER-2902"),
    /** 取消发布 */
    CANCEL_DEPLOY_SUCCESS("SU-030"),
    CANCEL_DEPLOY_FAIL_BY_STATUS("ER-3001"),
    /** 强制完工 */
    FORCE_FINISH_SUCCESS("SU-040"),
    FORCE_FINISH_FAIL_BY_STATUS("ER-4001"),
    FORCE_FINISH_FAIL("ER-4002"),
    ;

    private final String value;

    ErrorCodeEnum(String value) {
        this.value = value;
    }

    @Override
    public String getValue() {
        return value;
    }

}
